name: RSpec

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # Setup Ruby
    # https://github.com/ruby/setup-ruby#single-job
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true

    # Setup Yarn
    - name: Setup Yarn
      uses: bahmutov/npm-install@v1

    # Build the middleman site
    - name: Build App
      env:
        RAILS_ENV: test
      run: |
        bundle exec middleman build --verbose

    # Run RSpec again the new change
    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rspec
